SPRANG-30 added Create-  tool window
simasnau/SprAngu pull request #18
Opened 2022-05-18 13:44 UTC by GMurnevaite

2022-05-18 14:17 UTC, AleksandrasMaliuginas requested changes
Dar reiks ant galo konfliktus išspręsti prieš merginant.

2022-05-18 14:17 UTC, AleksandrasMaliuginas commented on sprangu-front/src/app/components/header/header.component.html
> +    </ng-template>
Galima if'ą tsg į rauterLink'ą įdėt: `if isLogged ? 'createtoo/view' : 'register'`

2022-05-18 14:17 UTC, AleksandrasMaliuginas commented on sprangu-front/src/app/pages/create-tool/create-tool.component.html
> +            <br>
Geriau margin'us naudot, nes paskui išsikraipo vaizdas.

2022-05-18 14:17 UTC, AleksandrasMaliuginas commented on sprangu-front/src/app/pages/create-tool/create-tool.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
spec.ts gali išvis ištrinti, nes mes jo niekur nenaudojam

2022-05-18 14:17 UTC, AleksandrasMaliuginas commented on sprangu-front/src/app/pages/create-tool/create-tool.component.ts
> +        // @ts-ignore
Kodėl čia reikia šito ignoro?

2022-05-22 17:15 UTC, JuozapasG commented on sprangu-front/src/app/pages/create-tool/create-tool.component.ts
> +        // @ts-ignore
Čia todėl, nes event.targer gali būti null, bet jis nebus niekad null, jeigu nebus metodas iš kitus kviečiamas, nes kviečia tik onChange inpute html

2022-05-22 17:15 UTC, JuozapasG approved these changes

2022-05-23 08:28 UTC, AleksandrasMaliuginas approved these changes

2022-05-23 08:28 UTC, merged